/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'customerName' : string,
  'status' : BookingStatus,
  'assignedPhotographer' : [] | [Principal],
  'customerEmail' : string,
  'packageId' : string,
  'eventDate' : string,
}
export type BookingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'confirmed' : null };
export type Category = { 'receptions' : null } |
  { 'weddings' : null } |
  { 'preWedding' : null };
export type ExternalBlob = Uint8Array;
export interface GalleryCategoryMeta { 'name' : string, 'description' : string }
export interface HomepageContent {
  'heroSubtitle' : string,
  'callOutButtonText' : string,
  'heroTitle' : string,
  'heroBackgroundImage' : string,
}
export interface Package {
  'id' : string,
  'name' : string,
  'description' : string,
  'price' : bigint,
  'isVideo' : boolean,
}
export interface Photo {
  'id' : string,
  'title' : string,
  'blob' : ExternalBlob,
  'isFeatured' : boolean,
  'category' : Category,
}
export interface SitewideContent {
  'servicesDescription' : string,
  'bookingIntro' : string,
  'footerContent' : string,
}
export interface SpecialMomentGallery {
  'id' : string,
  'title' : string,
  'date' : string,
  'description' : string,
  'photoIds' : Array<string>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'title' : string,
  'blob' : ExternalBlob,
  'isFeatured' : boolean,
  'category' : Category,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  /**
   * / Booking management
   */
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPhoto' : ActorMethod<
    [{ 'title' : string, 'blob' : ExternalBlob, 'category' : Category }],
    string
  >,
  /**
   * / Portfolio management - Admin only
   */
  'addVideo' : ActorMethod<
    [{ 'title' : string, 'blob' : ExternalBlob, 'category' : Category }],
    string
  >,
  'approveBooking' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPhotographer' : ActorMethod<[string, Principal], undefined>,
  /**
   * / Booking system - Public, customers can book without authentication
   */
  'createBooking' : ActorMethod<
    [
      {
        'customerName' : string,
        'customerEmail' : string,
        'packageId' : string,
        'eventDate' : string,
      },
    ],
    string
  >,
  /**
   * / Package management - Admin only
   */
  'createPackage' : ActorMethod<
    [
      {
        'name' : string,
        'description' : string,
        'price' : bigint,
        'isVideo' : boolean,
      },
    ],
    string
  >,
  /**
   * / Special Moments Gallery Management
   */
  'createSpecialMomentGallery' : ActorMethod<
    [
      {
        'title' : string,
        'date' : string,
        'description' : string,
        'photoIds' : Array<string>,
      },
    ],
    string
  >,
  'deletePackage' : ActorMethod<[string], undefined>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  /**
   * / Admin Booking Management - Admin only
   */
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllCategoryMeta' : ActorMethod<
    [],
    Array<[Category, GalleryCategoryMeta]>
  >,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getAllSpecialMomentGalleries' : ActorMethod<[], Array<SpecialMomentGallery>>,
  /**
   * / User Profile Management
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryMeta' : ActorMethod<[Category], [] | [GalleryCategoryMeta]>,
  'getHomepageContent' : ActorMethod<[], HomepageContent>,
  /**
   * / Package browsing - Public, no authentication required
   */
  'getPackages' : ActorMethod<[boolean], Array<Package>>,
  'getPhotos' : ActorMethod<[], Array<Photo>>,
  'getPhotosByCategory' : ActorMethod<[Category], Array<Photo>>,
  'getSitewideContent' : ActorMethod<[], SitewideContent>,
  'getSpecialMomentGalleriesByDate' : ActorMethod<
    [string],
    Array<SpecialMomentGallery>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Public portfolio access - No authentication required
   */
  'getVideos' : ActorMethod<[], Array<Video>>,
  'getVideosByCategory' : ActorMethod<[Category], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectBooking' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPhotoFeatured' : ActorMethod<[string, boolean], undefined>,
  'setVideoFeatured' : ActorMethod<[string, boolean], undefined>,
  'updateBookingStatus' : ActorMethod<[string, BookingStatus], undefined>,
  /**
   * / Gallery Category Meta Management
   */
  'updateCategoryMeta' : ActorMethod<
    [Category, GalleryCategoryMeta],
    undefined
  >,
  /**
   * / Homepage Content Management
   */
  'updateHomepageContent' : ActorMethod<[HomepageContent], undefined>,
  'updatePackage' : ActorMethod<
    [
      string,
      {
        'name' : string,
        'description' : string,
        'price' : bigint,
        'isVideo' : boolean,
      },
    ],
    undefined
  >,
  /**
   * / Sitewide Content Management
   */
  'updateSitewideContent' : ActorMethod<[SitewideContent], undefined>,
  'updateSpecialMomentGallery' : ActorMethod<
    [string, SpecialMomentGallery],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];