/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'receptions' : IDL.Null,
  'weddings' : IDL.Null,
  'preWedding' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'assignedPhotographer' : IDL.Opt(IDL.Principal),
  'customerEmail' : IDL.Text,
  'packageId' : IDL.Text,
  'eventDate' : IDL.Text,
});
export const GalleryCategoryMeta = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Package = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
  'isVideo' : IDL.Bool,
});
export const SpecialMomentGallery = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'photoIds' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const HomepageContent = IDL.Record({
  'heroSubtitle' : IDL.Text,
  'callOutButtonText' : IDL.Text,
  'heroTitle' : IDL.Text,
  'heroBackgroundImage' : IDL.Text,
});
export const Photo = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'isFeatured' : IDL.Bool,
  'category' : Category,
});
export const SitewideContent = IDL.Record({
  'servicesDescription' : IDL.Text,
  'bookingIntro' : IDL.Text,
  'footerContent' : IDL.Text,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'isFeatured' : IDL.Bool,
  'category' : Category,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPhoto' : IDL.Func(
      [
        IDL.Record({
          'title' : IDL.Text,
          'blob' : ExternalBlob,
          'category' : Category,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'addVideo' : IDL.Func(
      [
        IDL.Record({
          'title' : IDL.Text,
          'blob' : ExternalBlob,
          'category' : Category,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'approveBooking' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPhotographer' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Record({
          'customerName' : IDL.Text,
          'customerEmail' : IDL.Text,
          'packageId' : IDL.Text,
          'eventDate' : IDL.Text,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'createPackage' : IDL.Func(
      [
        IDL.Record({
          'name' : IDL.Text,
          'description' : IDL.Text,
          'price' : IDL.Nat,
          'isVideo' : IDL.Bool,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'createSpecialMomentGallery' : IDL.Func(
      [
        IDL.Record({
          'title' : IDL.Text,
          'date' : IDL.Text,
          'description' : IDL.Text,
          'photoIds' : IDL.Vec(IDL.Text),
        }),
      ],
      [IDL.Text],
      [],
    ),
  'deletePackage' : IDL.Func([IDL.Text], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllCategoryMeta' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Category, GalleryCategoryMeta))],
      ['query'],
    ),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAllSpecialMomentGalleries' : IDL.Func(
      [],
      [IDL.Vec(SpecialMomentGallery)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryMeta' : IDL.Func(
      [Category],
      [IDL.Opt(GalleryCategoryMeta)],
      ['query'],
    ),
  'getHomepageContent' : IDL.Func([], [HomepageContent], ['query']),
  'getPackages' : IDL.Func([IDL.Bool], [IDL.Vec(Package)], ['query']),
  'getPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getPhotosByCategory' : IDL.Func([Category], [IDL.Vec(Photo)], ['query']),
  'getSitewideContent' : IDL.Func([], [SitewideContent], ['query']),
  'getSpecialMomentGalleriesByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SpecialMomentGallery)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getVideosByCategory' : IDL.Func([Category], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectBooking' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPhotoFeatured' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setVideoFeatured' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
  'updateCategoryMeta' : IDL.Func([Category, GalleryCategoryMeta], [], []),
  'updateHomepageContent' : IDL.Func([HomepageContent], [], []),
  'updatePackage' : IDL.Func(
      [
        IDL.Text,
        IDL.Record({
          'name' : IDL.Text,
          'description' : IDL.Text,
          'price' : IDL.Nat,
          'isVideo' : IDL.Bool,
        }),
      ],
      [],
      [],
    ),
  'updateSitewideContent' : IDL.Func([SitewideContent], [], []),
  'updateSpecialMomentGallery' : IDL.Func(
      [IDL.Text, SpecialMomentGallery],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'receptions' : IDL.Null,
    'weddings' : IDL.Null,
    'preWedding' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'assignedPhotographer' : IDL.Opt(IDL.Principal),
    'customerEmail' : IDL.Text,
    'packageId' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  const GalleryCategoryMeta = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Package = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
    'isVideo' : IDL.Bool,
  });
  const SpecialMomentGallery = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'photoIds' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const HomepageContent = IDL.Record({
    'heroSubtitle' : IDL.Text,
    'callOutButtonText' : IDL.Text,
    'heroTitle' : IDL.Text,
    'heroBackgroundImage' : IDL.Text,
  });
  const Photo = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'isFeatured' : IDL.Bool,
    'category' : Category,
  });
  const SitewideContent = IDL.Record({
    'servicesDescription' : IDL.Text,
    'bookingIntro' : IDL.Text,
    'footerContent' : IDL.Text,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'isFeatured' : IDL.Bool,
    'category' : Category,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPhoto' : IDL.Func(
        [
          IDL.Record({
            'title' : IDL.Text,
            'blob' : ExternalBlob,
            'category' : Category,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'addVideo' : IDL.Func(
        [
          IDL.Record({
            'title' : IDL.Text,
            'blob' : ExternalBlob,
            'category' : Category,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'approveBooking' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPhotographer' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Record({
            'customerName' : IDL.Text,
            'customerEmail' : IDL.Text,
            'packageId' : IDL.Text,
            'eventDate' : IDL.Text,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'createPackage' : IDL.Func(
        [
          IDL.Record({
            'name' : IDL.Text,
            'description' : IDL.Text,
            'price' : IDL.Nat,
            'isVideo' : IDL.Bool,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'createSpecialMomentGallery' : IDL.Func(
        [
          IDL.Record({
            'title' : IDL.Text,
            'date' : IDL.Text,
            'description' : IDL.Text,
            'photoIds' : IDL.Vec(IDL.Text),
          }),
        ],
        [IDL.Text],
        [],
      ),
    'deletePackage' : IDL.Func([IDL.Text], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllCategoryMeta' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Category, GalleryCategoryMeta))],
        ['query'],
      ),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAllSpecialMomentGalleries' : IDL.Func(
        [],
        [IDL.Vec(SpecialMomentGallery)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryMeta' : IDL.Func(
        [Category],
        [IDL.Opt(GalleryCategoryMeta)],
        ['query'],
      ),
    'getHomepageContent' : IDL.Func([], [HomepageContent], ['query']),
    'getPackages' : IDL.Func([IDL.Bool], [IDL.Vec(Package)], ['query']),
    'getPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getPhotosByCategory' : IDL.Func([Category], [IDL.Vec(Photo)], ['query']),
    'getSitewideContent' : IDL.Func([], [SitewideContent], ['query']),
    'getSpecialMomentGalleriesByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SpecialMomentGallery)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getVideosByCategory' : IDL.Func([Category], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectBooking' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPhotoFeatured' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setVideoFeatured' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
    'updateCategoryMeta' : IDL.Func([Category, GalleryCategoryMeta], [], []),
    'updateHomepageContent' : IDL.Func([HomepageContent], [], []),
    'updatePackage' : IDL.Func(
        [
          IDL.Text,
          IDL.Record({
            'name' : IDL.Text,
            'description' : IDL.Text,
            'price' : IDL.Nat,
            'isVideo' : IDL.Bool,
          }),
        ],
        [],
        [],
      ),
    'updateSitewideContent' : IDL.Func([SitewideContent], [], []),
    'updateSpecialMomentGallery' : IDL.Func(
        [IDL.Text, SpecialMomentGallery],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };